# Generated by Django 4.2.25 on 2025-11-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='subnet_mask',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
