# Generated by Django 4.2.25 on 2025-11-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_device_subnet_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
