# Generated by Django 4.2.25 on 2025-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_device_password_encrypted_device_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='password_encrypted',
            new_name='snmp_aes_passwd',
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
