# Generated by Django 4.2.25 on 2025-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_rename_password_encrypted_device_snmp_aes_passwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='snmp_aes_passwd',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_password',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.TextField(),
        ),
    ]
